config/routes.rb
Rails.application.routes.draw do
  get 'principals/quienes'

  get 'principals/blog'

  get 'principals/post'

  get 'principals/ventas2'

  get 'principals/ventas1'

  resources :principals

  resources :canalingresos

  resources :temas

  resources :areas

  root 'principals#index'

end

app/models/canalingreso.rb
class Canalingreso < ActiveRecord::Base
end

app/controllers/canalingresos_controller.rb
class CanalingresosController < ApplicationController
  before_action :set_canalingreso, only: [:show, :edit, :update, :destroy]

  # GET /canalingresos
  # GET /canalingresos.json
  def index
    @canalingresos = Canalingreso.all
  end

  # GET /canalingresos/1
  # GET /canalingresos/1.json
  def show
  end

  # GET /canalingresos/new
  def new
    @canalingreso = Canalingreso.new
  end

  # GET /canalingresos/1/edit
  def edit
  end

  # POST /canalingresos
  # POST /canalingresos.json
  def create
    @canalingreso = Canalingreso.new(canalingreso_params)

    respond_to do |format|
      if @canalingreso.save
        format.html { redirect_to @canalingreso, notice: 'Canalingreso was successfully created.' }
        format.json { render :show, status: :created, location: @canalingreso }
      else
        format.html { render :new }
        format.json { render json: @canalingreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /canalingresos/1
  # PATCH/PUT /canalingresos/1.json
  def update
    respond_to do |format|
      if @canalingreso.update(canalingreso_params)
        format.html { redirect_to @canalingreso, notice: 'Canalingreso was successfully updated.' }
        format.json { render :show, status: :ok, location: @canalingreso }
      else
        format.html { render :edit }
        format.json { render json: @canalingreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /canalingresos/1
  # DELETE /canalingresos/1.json
  def destroy
    @canalingreso.destroy
    respond_to do |format|
      format.html { redirect_to canalingresos_url, notice: 'Canalingreso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_canalingreso
      @canalingreso = Canalingreso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def canalingreso_params
      params.require(:canalingreso).permit(:cin_titulo, :cin_desc)
    end
end

app/helpers/canalingresos_helper.rb
module CanalingresosHelper
end

app/views/canalingresos/_form.html.erb
<%= form_for(@canalingreso) do |f| %>
  <% if @canalingreso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@canalingreso.errors.count, "error") %> prohibited this canalingreso from being saved:</h2>

      <ul>
      <% @canalingreso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cin_titulo %><br>
    <%= f.text_field :cin_titulo %>
  </div>
  <div class="field">
    <%= f.label :cin_desc %><br>
    <%= f.text_area :cin_desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/canalingresos/edit.html.erb
<h1>Editing Canalingreso</h1>

<%= render 'form' %>

<%= link_to 'Show', @canalingreso %> |
<%= link_to 'Back', canalingresos_path %>

app/views/canalingresos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Canalingresos</h1>

<table>
  <thead>
    <tr>
      <th>Cin titulo</th>
      <th>Cin desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @canalingresos.each do |canalingreso| %>
      <tr>
        <td><%= canalingreso.cin_titulo %></td>
        <td><%= canalingreso.cin_desc %></td>
        <td><%= link_to 'Show', canalingreso %></td>
        <td><%= link_to 'Edit', edit_canalingreso_path(canalingreso) %></td>
        <td><%= link_to 'Destroy', canalingreso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Canalingreso', new_canalingreso_path %>

app/views/canalingresos/new.html.erb
<h1>New Canalingreso</h1>

<%= render 'form' %>

<%= link_to 'Back', canalingresos_path %>

app/views/canalingresos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cin titulo:</strong>
  <%= @canalingreso.cin_titulo %>
</p>

<p>
  <strong>Cin desc:</strong>
  <%= @canalingreso.cin_desc %>
</p>

<%= link_to 'Edit', edit_canalingreso_path(@canalingreso) %> |
<%= link_to 'Back', canalingresos_path %>