config/routes.rb
Rails.application.routes.draw do
  get 'principals/quienes'

  get 'principals/blog'

  get 'principals/post'

  get 'principals/ventas2'

  get 'principals/ventas1'

  resources :principals

  resources :canalingresos

  resources :temas

  resources :areas

  root 'principals#index'

end

app/models/principal.rb
class Principal < ActiveRecord::Base
  belongs_to :tema
  belongs_to :canalingreso
end

app/controllers/principals_controller.rb
class PrincipalsController < ApplicationController
  before_action :set_principal, only: [:show, :edit, :update, :destroy]

  # GET /principals
  # GET /principals.json
  def index
    @principals = Principal.all
  end

  # GET /principals/1
  # GET /principals/1.json
  def show
  end

  # GET /principals/new
  def new
    @principal = Principal.new
    @principal.mov_obs = params[:motivo]
    #@principal = Principal.new
  end

  # GET /principals/1/edit
  def edit
  end

  # POST /principals
  # POST /principals.json
  def create
    @principal = Principal.create(principal_params)

    ContactMailer.contact_email(@principal).deliver
  end

  # PATCH/PUT /principals/1
  # PATCH/PUT /principals/1.json
  def update
    respond_to do |format|
      if @principal.update(principal_params)
        format.html { redirect_to @principal, notice: 'Principal was successfully updated.' }
        format.json { render :show, status: :ok, location: @principal }
      else
        format.html { render :edit }
        format.json { render json: @principal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /principals/1
  # DELETE /principals/1.json
  def destroy
    @principal.destroy
    respond_to do |format|
      format.html { redirect_to principals_url, notice: 'Principal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def post

    @post_titulo = params[:pst_titulo]
    @post_imagen01 = params[:pst_imagen01]
    @post_badge = params[:pst_badge]

    @post_subtit01a = params[:pst_subtit01a]
    @post_subtit01s = params[:pst_subtit01s]
    @post_subtit01b = params[:pst_subtit01b]

    # subtitulo 00

    @post_subtit00 = params[:pst_subtit00]

    @post_link00a1 = params[:pst_link00a1]
    @post_link00a2 = params[:pst_link00a2]
    @post_link00b1 = params[:pst_link00b1]
    @post_link00b2 = params[:pst_link00b2]
    @post_link00c1 = params[:pst_link00c1]
    @post_link00c2 = params[:pst_link00c2]
    @post_link00d1 = params[:pst_link00d1]
    @post_link00d2 = params[:pst_link00d2]
    @post_link00e1 = params[:pst_link00e1]
    @post_link00e2 = params[:pst_link00e2]

    # primer subtitulo

    @post_subtit02a = params[:pst_subtit02a]
    @post_subtit02s = params[:pst_subtit02s]
    @post_subtit02b = params[:pst_subtit02b]

    @post_texto02a = params[:pst_texto02a]
    @post_texto02a1 = params[:pst_texto02a1]
    @post_texto02a2 = params[:pst_texto02a2]
    @post_texto02a3 = params[:pst_texto02a3]
    @post_texto02a4 = params[:pst_texto02a4]
    @post_texto02a5 = params[:pst_texto02a5]

    @post_texto02b = params[:pst_texto02b]
    @post_texto02b1 = params[:pst_texto02b1]
    @post_texto02b2 = params[:pst_texto02b2]
    @post_texto02b3 = params[:pst_texto02b3]
    @post_texto02b4 = params[:pst_texto02b4]
    @post_texto02b5 = params[:pst_texto02b5]

    @post_texto02c = params[:pst_texto02c]
    @post_texto02c1 = params[:pst_texto02c1]
    @post_texto02c2 = params[:pst_texto02c2]
    @post_texto02c3 = params[:pst_texto02c3]
    @post_texto02c4 = params[:pst_texto02c4]
    @post_texto02c5 = params[:pst_texto02c5]

    @post_texto02d = params[:pst_texto02d]
    @post_texto02d1 = params[:pst_texto02d1]
    @post_texto02d2 = params[:pst_texto02d2]
    @post_texto02d3 = params[:pst_texto02d3]
    @post_texto02d4 = params[:pst_texto02d4]
    @post_texto02d5 = params[:pst_texto02d5]

    @post_texto02e = params[:pst_texto02e]
    @post_texto02e1 = params[:pst_texto02e1]
    @post_texto02e2 = params[:pst_texto02e2]
    @post_texto02e3 = params[:pst_texto02e3]
    @post_texto02e4 = params[:pst_texto02e4]
    @post_texto02e5 = params[:pst_texto02e5]

    @post_texto02f = params[:pst_texto02f]
    @post_texto02f1 = params[:pst_texto02f1]
    @post_texto02f2 = params[:pst_texto02f2]
    @post_texto02f3 = params[:pst_texto02f3]
    @post_texto02f4 = params[:pst_texto02f4]
    @post_texto02f5 = params[:pst_texto02f5]

    @post_texto02g = params[:pst_texto02g]
    @post_texto02g1 = params[:pst_texto02g1]
    @post_texto02g2 = params[:pst_texto02g2]
    @post_texto02g3 = params[:pst_texto02g3]
    @post_texto02g4 = params[:pst_texto02g4]
    @post_texto02g5 = params[:pst_texto02g5]

    # segundo subtitulo

    @post_subtit03a = params[:pst_subtit03a]
    @post_subtit03s = params[:pst_subtit03s]
    @post_subtit03b = params[:pst_subtit03b]

    @post_texto03a = params[:pst_texto03a]
    @post_texto03a1 = params[:pst_texto03a1]
    @post_texto03a2 = params[:pst_texto03a2]
    @post_texto03a3 = params[:pst_texto03a3]
    @post_texto03a4 = params[:pst_texto03a4]
    @post_texto03a5 = params[:pst_texto03a5]

    @post_texto03b = params[:pst_texto03b]
    @post_texto03b1 = params[:pst_texto03b1]
    @post_texto03b2 = params[:pst_texto03b2]
    @post_texto03b3 = params[:pst_texto03b3]
    @post_texto03b4 = params[:pst_texto03b4]
    @post_texto03b5 = params[:pst_texto03b5]

    @post_texto03c = params[:pst_texto03c]
    @post_texto03c1 = params[:pst_texto03c1]
    @post_texto03c2 = params[:pst_texto03c2]
    @post_texto03c3 = params[:pst_texto03c3]
    @post_texto03c4 = params[:pst_texto03c4]
    @post_texto03c5 = params[:pst_texto03c5]

    @post_texto03d = params[:pst_texto03d]
    @post_texto03d1 = params[:pst_texto03d1]
    @post_texto03d2 = params[:pst_texto03d2]
    @post_texto03d3 = params[:pst_texto03d3]
    @post_texto03d4 = params[:pst_texto03d4]
    @post_texto03d5 = params[:pst_texto03d5]

    @post_texto03e = params[:pst_texto03e]
    @post_texto03e1 = params[:pst_texto03e1]
    @post_texto03e2 = params[:pst_texto03e2]
    @post_texto03e3 = params[:pst_texto03e3]
    @post_texto03e4 = params[:pst_texto03e4]
    @post_texto03e5 = params[:pst_texto03e5]

    @post_texto03f = params[:pst_texto03f]
    @post_texto03f1 = params[:pst_texto03f1]
    @post_texto03f2 = params[:pst_texto03f2]
    @post_texto03f3 = params[:pst_texto03f3]
    @post_texto03f4 = params[:pst_texto03f4]
    @post_texto03f5 = params[:pst_texto03f5]

    @post_texto03g = params[:pst_texto03g]
    @post_texto03g1 = params[:pst_texto03g1]
    @post_texto03g2 = params[:pst_texto03g2]
    @post_texto03g3 = params[:pst_texto03g3]
    @post_texto03g4 = params[:pst_texto03g4]
    @post_texto03g5 = params[:pst_texto03g5]

    # cuarto subtitulo

    @post_subtit04a = params[:pst_subtit04a]
    @post_subtit04s = params[:pst_subtit04s]
    @post_subtit04b = params[:pst_subtit04b]

    @post_texto04a = params[:pst_texto04a]
    @post_texto04a1 = params[:pst_texto04a1]
    @post_texto04a2 = params[:pst_texto04a2]
    @post_texto04a3 = params[:pst_texto04a3]
    @post_texto04a4 = params[:pst_texto04a4]
    @post_texto04a5 = params[:pst_texto04a5]

    @post_texto04b = params[:pst_texto04b]
    @post_texto04b1 = params[:pst_texto04b1]
    @post_texto04b2 = params[:pst_texto04b2]
    @post_texto04b3 = params[:pst_texto04b3]
    @post_texto04b4 = params[:pst_texto04b4]
    @post_texto04b5 = params[:pst_texto04b5]

    @post_texto04c = params[:pst_texto04c]
    @post_texto04c1 = params[:pst_texto04c1]
    @post_texto04c2 = params[:pst_texto04c2]
    @post_texto04c3 = params[:pst_texto04c3]
    @post_texto04c4 = params[:pst_texto04c4]
    @post_texto04c5 = params[:pst_texto04c5]

    @post_texto04d = params[:pst_texto04d]
    @post_texto04d1 = params[:pst_texto04d1]
    @post_texto04d2 = params[:pst_texto04d2]
    @post_texto04d3 = params[:pst_texto04d3]
    @post_texto04d4 = params[:pst_texto04d4]
    @post_texto04d5 = params[:pst_texto04d5]

    @post_texto04e = params[:pst_texto04e]
    @post_texto04e1 = params[:pst_texto04e1]
    @post_texto04e2 = params[:pst_texto04e2]
    @post_texto04e3 = params[:pst_texto04e3]
    @post_texto04e4 = params[:pst_texto04e4]
    @post_texto04e5 = params[:pst_texto04e5]

    @post_texto04f = params[:pst_texto04f]
    @post_texto04f1 = params[:pst_texto04f1]
    @post_texto04f2 = params[:pst_texto04f2]
    @post_texto04f3 = params[:pst_texto04f3]
    @post_texto04f4 = params[:pst_texto04f4]
    @post_texto04f5 = params[:pst_texto04f5]

    @post_texto04g = params[:pst_texto04g]
    @post_texto04g1 = params[:pst_texto04g1]
    @post_texto04g2 = params[:pst_texto04g2]
    @post_texto04g3 = params[:pst_texto04g3]
    @post_texto04g4 = params[:pst_texto04g4]
    @post_texto04g5 = params[:pst_texto04g5]

    # quinto subtitulo

    @post_subtit05a = params[:pst_subtit05a]
    @post_subtit05s = params[:pst_subtit05s]
    @post_subtit05b = params[:pst_subtit05b]

    @post_texto05a = params[:pst_texto05a]
    @post_texto05a1 = params[:pst_texto05a1]
    @post_texto05a2 = params[:pst_texto05a2]
    @post_texto05a3 = params[:pst_texto05a3]
    @post_texto05a4 = params[:pst_texto05a4]
    @post_texto05a5 = params[:pst_texto05a5]

    @post_texto05b = params[:pst_texto05b]
    @post_texto05b1 = params[:pst_texto05b1]
    @post_texto05b2 = params[:pst_texto05b2]
    @post_texto05b3 = params[:pst_texto05b3]
    @post_texto05b4 = params[:pst_texto05b4]
    @post_texto05b5 = params[:pst_texto05b5]

    @post_texto05c = params[:pst_texto05c]
    @post_texto05c1 = params[:pst_texto05c1]
    @post_texto05c2 = params[:pst_texto05c2]
    @post_texto05c3 = params[:pst_texto05c3]
    @post_texto05c4 = params[:pst_texto05c4]
    @post_texto05c5 = params[:pst_texto05c5]

    @post_texto05d = params[:pst_texto05d]
    @post_texto05d1 = params[:pst_texto05d1]
    @post_texto05d2 = params[:pst_texto05d2]
    @post_texto05d3 = params[:pst_texto05d3]
    @post_texto05d4 = params[:pst_texto05d4]
    @post_texto05d5 = params[:pst_texto05d5]

    @post_texto05e = params[:pst_texto05e]
    @post_texto05e1 = params[:pst_texto05e1]
    @post_texto05e2 = params[:pst_texto05e2]
    @post_texto05e3 = params[:pst_texto05e3]
    @post_texto05e4 = params[:pst_texto05e4]
    @post_texto05e5 = params[:pst_texto05e5]

    @post_texto05f = params[:pst_texto05f]
    @post_texto05f1 = params[:pst_texto05f1]
    @post_texto05f2 = params[:pst_texto05f2]
    @post_texto05f3 = params[:pst_texto05f3]

app/helpers/principals_helper.rb
module PrincipalsHelper
end

app/views/principals/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for(@principal, remote: true) do |f| %>

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

        <% if @principal.mov_obs.include? "Blog" %>
          <h3>¿Quieres mejorar tu Negocio?</h3>

        <% elsif @principal.mov_obs.include? "txaShop" %>
          <h3>¿Quieres aumentar tus Ventas?</h3>
          <% elsif @principal.mov_obs.include? "txaVentas" %>
            <h3>¿Quieres aumentar tus Ventas?</h3>
            <% elsif @principal.mov_obs.include? "txaVision" %>
              <h3>¿Quieres aumentar tus Ventas?</h3>

        <% elsif @principal.mov_obs.include? "txaCostos" %>
          <h3>¿Quieres reducir los Costos?</h3>

        <% elsif @principal.mov_obs.include? "menu" %>
          <h3>¿Quieres comunicarte con nosotros?</h3>

        <% end %>

      </div>

      <div id="div-modal-body" class="modal-body">

        <ul class="errors"></ul>

        <h4 class="modal-header-h4">¡Anótate Gratis y te enviaremos<br/>Información útil para tu Pyme!</h4>

        <div class="row">
          <div class="field col-xs-12 col-sm-12 col-md-12">
            <%= f.text_field :con_nombre, :required => true, :placeholder => "Ingrese su Nombre...", :class=>"form-control" %>
          </div>
        </div>
        <div class="field">
          <%= f.text_field :con_mail, :required => true, :placeholder => "Ingrese su email...", :class=>"form-control" %>
        </div>
        <div class="field hide">
          <%= f.text_area :mov_obs, :class=>"form-control" %>
        </div>
      </div>

      <% if @principal.mov_obs.include? "txaShop" %>
        <h4 class="modal-header-h4">Nos contactaremos contingo<br/>Hoy mismo</h4>
        <% elsif @principal.mov_obs.include? "txaVentas" %>
          <h4 class="modal-header-h4">Nos contactaremos contingo<br/>Hoy mismo</h4>
          <% elsif @principal.mov_obs.include? "txaVision" %>
            <h4 class="modal-header-h4">Nos contactaremos contingo<br/>Hoy mismo</h4>
            <% elsif @principal.mov_obs.include? "txaCostos" %>
              <h4 class="modal-header-h4">Nos contactaremos contingo<br/>Hoy mismo</h4>
              <% elsif @principal.mov_obs.include? "menu" %>
                <h4 class="modal-header-h4">Nos contactaremos contingo<br/>Hoy mismo</h4>
      <% end %>

      <div id="msgOK">
      </div>

      <div class="modal-footer">
        <div class="col-xs-6 col-sm-7 col-md-7 col-lg-7">
          <%= image_tag("texhablanco100x40.jpg") %>
        </div>
        <div id="divMeAnoto" class="col-xs-6 col-sm-4 col-md-4 col-lg-4">
          <%= f.submit '¡Me Anoto!', :class=>"btn btn-outline-inverse btn-md btn-idx3", :id=>"gc-aceptar" %>
        </div>
      </div>
    <% end %>
  </div>
</div>



<!-- 
        <%= link_to "Cancelar", "#", class: "btn btn-outline-inverse btn-md btn-idx3", data: {dismiss: "modal"} %>
-->

app/views/principals/_save.js.erb
$("#product-modal").modal("hide")

app/views/principals/create.js.erb
<%= render "save" %>

app/views/principals/index.html.erb
<div id="product-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 div-img", id="pp0" >
  <%= image_tag "maina.jpg", class: "img-responsive img-ppal"%>
  <%= image_tag "mainb.jpg", class: "img-responsive img-ppal2"%>
</div>

<div class="carousel-ppal col-xs-12 col-sm-12 col-md-12 col-lg-12", id="pp1" >
  <div id="myCarousel" class="carousel slide" data-ride="carousel"> <!-- data-ride="carousel" -->
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active">
      </li>
      <li data-target="#myCarousel" data-slide-to="1">
      </li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
          <div class="carousel-caption">
          <h1>Aumente sus <span>Ventas</span></h1>
          <h3>Productos flexibles, de Alta Calidad<br/>y Rapidos de implementar!!</h3>
          <%= link_to  'Ver mas...', "#pp", :class=>"btn-idx btn-font mov-suave btn-lg" %>
      </div>
      </div>
      <div class="item">
        <div class="carousel-caption">
          <h1>Reduzca los <span>Costos</span></h1>
          <h3>Examine sus Costos<br/>con formulas de Ingenieria.</h3>
          <%= link_to  'Ver mas...',"#ppp", :class=>"btn-idx btn-font mov-suave btn-lg" %>
        </div>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-hand-left" aria-hidden="true">
      </span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-hand-right" aria-hidden="true">
      </span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div> <!-- <div class="carousel-ppal"> -->

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 div-img", id="pp" >
  <%= image_tag "Textura-ventas.jpg", class: "img-responsive img-ppal-vtas-ctos"%>
  <div id="myCarousel2" class="carousel slide carousel-ppal2"> <!-- data-ride="carousel" -->
    <!-- Indicators -->
    <ol class="carousel-indicators carousel-indicators2">
      <li data-target="#myCarousel2" data-slide-to="0" class="active">
      </li>
      <li data-target="#myCarousel2" data-slide-to="1">
      </li>
      <li data-target="#myCarousel2" data-slide-to="2">
      </li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= link_to 'Expliquenme mas', principals_ventas1_path, :class=>"btn-idx2 btn-font1 btn-lg" %>
        <%= image_tag "diseño.png", class: "img_vta1"  %>
        <div class="carousel-caption2">
          <h1>Su WEB en 72hs</h1>
          <h3> Sea mas conocido en su zona<br/>
              Diseños de alta calidad (tambien Tablet y Celular)
          </h3>
        </div>
      </div>
      <div class="item">
        <%= link_to 'Expliquenme mas', principals_ventas2_path, :class=>"btn-idx2 btn-font1 btn-lg" %>
<!--        <%= link_to 'Quiero Charlar!', new_principal_path, :class=>"btn btn-success btn-md btn-idx2" %> -->
        <%= image_tag "camara-900x550.png", class: "img_vta2"  %>
        <div class="carousel-caption2">
          <h1>Control Visual 360º</h1>
          <h3>Observe sus Locales y Empleados.<br/>
             desde su PC, Tablet o Celular.</h3>
        </div>
      </div>
      <div class="item">
        <%= link_to 'Tomemos un Cafe', new_principal_path(:motivo => "txaVentas - Cafe"), remote: true, class: "btn-idx2 btn-font1 btn-lg" %>
        <%= image_tag "relax-900x550.jpg", class: "img_vta3"  %>
        <div class="carousel-caption2">
          <h1>Mejore la </span>Rentabilidad</span> <br/> de su Negocio</h1>
          <h3>...y Relajese!</h3>
        </div>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control caro-cont2" href="#myCarousel2" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-hand-left" aria-hidden="true">
      </span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control caro-cont2" href="#myCarousel2" role="button" data-slide="next">
      <span class="glyphicon glyphicon-hand-right" aria-hidden="true">
      </span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 div-img", id="ppp" >
  <%= image_tag "Textura-costos.jpg", class: "img-responsive img-ppal-vtas-ctos"%>
  <div id="myCarousel3" class="carousel slide carousel-ppal2" > <!-- data-ride="carousel" -->
    <!-- Indicators -->
    <ol class="carousel-indicators carousel-indicators2">
      <li data-target="#myCarousel3" data-slide-to="0" class="active">
      </li>
      <li data-target="#myCarousel3" data-slide-to="1">
      </li>
      <li data-target="#myCarousel3" data-slide-to="2">
      </li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= link_to 'Expliquenme mas', new_principal_path(:motivo => "txaCostos - reduccion"), remote: true, :class=>"btn-idx2 btn-font1 btn-lg" %>
        <%= image_tag "costosgastos.jpg", class: "img_vta4"  %>
        <div class="carousel-caption2">
          <h1>No pierda mas dinero!</h1>
          <h3>Organice sus Costos.<br/>
              Nuestros Ingenieros lo ayudaran.
          </h3>
        </div>
      </div>
      <div class="item">
        <%= link_to 'Expliquenme mas', new_principal_path(:motivo => "txaCostos - unificada"), remote: true, :class=>"btn-idx2 btn-font1 btn-lg" %>
        <%= image_tag "reporte889x571.png", class: "img_vta5"  %>
        <div class="carousel-caption2">
          <h1>Simplifique los<br/>Números de su Negocio</h1>
          <h3>Inventario, Ventas y Costos en 1 solo reporte!
          </h3>
        </div>
      </div>
      <div class="item">
        <%= link_to 'Tomemos un Cafe', new_principal_path(:motivo => "txaCostos - cafe"), remote: true, class: "btn-idx2 btn-font1 btn-lg" %>
        <%= image_tag "relax-900x550.jpg", class: "img_vta6"  %>
        <div class="carousel-caption2">
          <h1>Mejore la </span>Rentabilidad</span> <br/> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;de su Negocio</h1>
          <h3>...y Relajese!</h3>
        </div>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control caro-cont2" href="#myCarousel3" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-hand-left" aria-hidden="true">
      </span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control caro-cont2" href="#myCarousel3" role="button" data-slide="next">
      <span class="glyphicon glyphicon-hand-right" aria-hidden="true">
      </span>
      <span class="sr-only">Next</span>
    </a>
  </div>

</div>






































<!--

          <%= link_to  '<i class="glyphicon glyphicon-info-sign"></i>  + mas...'.html_safe, new_principal_path, :class=>"btn-idx btn-font1" %>


<p id="notice"><%= notice %></p>

<h1>Listing Principals</h1>

<table>
  <thead>
    <tr>
      <th>Con fecha</th>
      <th>Con nombre</th>
      <th>Tema</th>
      <th>Canalingreso</th>
      <th>Con mail</th>
      <th>Mov obs</th>
      <th>Con telefono</th>
      <th>Con mail sn</th>
      <th>Con telefono sn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @principals.each do |principal| %>
      <tr>
        <td><%= principal.con_fecha %></td>
        <td><%= principal.con_nombre %></td>
        <td><%= principal.tema %></td>
        <td><%= principal.canalingreso %></td>
        <td><%= principal.con_mail %></td>
        <td><%= principal.mov_obs %></td>
        <td><%= principal.con_telefono %></td>
        <td><%= principal.con_mail_sn %></td>
        <td><%= principal.con_telefono_sn %></td>
        <td><%= link_to 'Show', principal %></td>
        <td><%= link_to 'Edit', edit_principal_path(principal) %></td>
        <td><%= link_to 'Destroy', principal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Principal', new_principal_path %>

-->

app/views/principals/new.js.erb
$("#product-modal").html("<%= escape_javascript(render partial: 'new') %>" );
$("#product-modal").modal("show");
$('#product-modal').on('shown.bs.modal', function () {
/*	$('#principal_con_nombre').focus() */
});

app/views/principals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Con fecha:</strong>
  <%= @principal.con_fecha %>
</p>

<p>
  <strong>Con nombre:</strong>
  <%= @principal.con_nombre %>
</p>

<p>
  <strong>Tema:</strong>
  <%= @principal.tema %>
</p>

<p>
  <strong>Canalingreso:</strong>
  <%= @principal.canalingreso %>
</p>

<p>
  <strong>Con mail:</strong>
  <%= @principal.con_mail %>
</p>

<p>
  <strong>Mov obs:</strong>
  <%= @principal.mov_obs %>
</p>

<p>
  <strong>Con telefono:</strong>
  <%= @principal.con_telefono %>
</p>

<p>
  <strong>Con mail sn:</strong>
  <%= @principal.con_mail_sn %>
</p>

<p>
  <strong>Con telefono sn:</strong>
  <%= @principal.con_telefono_sn %>
</p>

<%= link_to 'Edit', edit_principal_path(@principal) %> |
<%= link_to 'Back', principals_path %>