config/routes.rb
Rails.application.routes.draw do
  get 'principals/quienes'

  get 'principals/blog'

  get 'principals/post'

  get 'principals/ventas2'

  get 'principals/ventas1'

  resources :principals

  resources :canalingresos

  resources :temas

  resources :areas

  root 'principals#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Texha Pymes</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="product-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
</div>

<nav class="navbar navbar-default navbar-fixed-top col-xs-9 col-sm-9 col-md-9 col-lg-9" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-principal">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to image_tag("texhablanco100x40.jpg"), {:action => "index", :controller => "principals", :anchor => "pp0"}, :class=>"mov-suave" %>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="menu-principal">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">VENTAS <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to "Tienda Virtual Pre-armada", {:action => "index", :controller => "principals", :anchor => "pp"}, :class=>"mov-suave" %>
            </li>
            <li>
              <%= link_to "Camaras de Vigilancia", {:action => "index", :controller => "principals", :anchor => "pp"}, :class=>"mov-suave" %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to 'Comunicarse con Nosotros', new_principal_path(:motivo => "menu - ventas"), remote: true %>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">COSTOS <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to "Reduccion de Costos", {:action => "index", :controller => "principals", :anchor => "ppp"}, :class=>"mov-suave" %>
            </li>
            <li>
              <%= link_to "Informacion Unificada de Ventas-Inventario-Gastos", {:action => "index", :controller => "principals", :anchor => "ppp"}, :class=>"mov-suave" %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to 'Comunicarse con Nosotros', new_principal_path(:motivo => "menu - costos"), remote: true %>
            </li>
          </ul>
        </li>
        <li>
          <%= link_to  '¿Quiénes Somos?', principals_quienes_path, :class=>"mov-suave" %>
        </li>
                        
        <li>
          <%= link_to 'Blog', principals_blog_path, :class=>"mov-suave", :id=>"btn-blog" %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!--<li><a href="#">Link</a></li> -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Ingresa al Sistema</a></li>
            <li><a href="#">Modificar Datos</a></li>
            <li><a href="#">Ingresar al Blog</a></li>
            <li class="divider"></li>
            <li><a href="#">Salir del Sistema</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<div class="container redes-soc">
  <div class="row">
    <div class="col-sm-1">
      <div class="sidebar-nav-fixed affix">
        <div class="well" style="padding-left: 3px;padding-right: 3px;padding-top: 10px;padding-bottom: 0px;background: rgba(0, 0, 0, 0);border:0px">
          <ul class="nav">
            <li class="nav-header" style="margin-bottom: 10px;">
              <a href="mailto:info@texhaarg.com" target="_blank" style="padding: 0px;background: rgba(0,0,0,0)">
              <%= image_tag "email_32.png", style: "width: 100%;" %>
              </a>
            </li>
            <div class="clear"></div>
            <li class="nav-header" style="margin-bottom: 10px;">
              <a href="http://www.linkedin.com/company/3374515?trk=tyah&amp;trkInfo=tas%3Atexha%20%2Cidx%3A1-2-2" target="_blank" style="padding: 0px;background: rgba(0,0,0,0)">
                <%= image_tag "linkedin_32.png", style: "width: 100%;" %></i>
              </a>
            </li>
            <div class="clear"></div>
            <li class="nav-header" style="margin-bottom: 10px;">
              <a href="http://www.facebook.com/texhaarg" target="_blank"  style="padding: 0px;background: rgba(0,0,0,0)">
                <%= image_tag "facebook_32.png", style: "width: 100%;" %></i>
              </a>
            </li>
            <div class="clear"></div>
            <li class="nav-header" style="margin-bottom: 10px;">
              <a href="http://www.twitter.com/texhaarg" target="_blank"  style="padding: 0px;background: rgba(0,0,0,0)">
                <%= image_tag "twitter_32.png", style: "width: 100%;" %></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="div-ppal">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/canvas-application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Texha Pymes</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="product-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<nav class="navbar navbar-default navbar-fixed-top col-xs-9 col-sm-9 col-md-9 col-lg-9">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-principal">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("texhablanco100x40.jpg"), "#pp0", :class=>"navbar-brand mov-suave" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="menu-principal">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">VENTAS <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to "Diseño Web", "#pp", :class=>"mov-suave" %>
            </li>
            <li>
              <%= link_to "Camaras de Vigilancia", "#pp", :class=>"mov-suave" %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to 'Comunicarse con Nosotros', new_principal_path, remote: true %>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">COSTOS <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to "Reduccion de Costos", "#ppp", :class=>"mov-suave" %>
            </li>
            <li>
              <%= link_to "Informacion Unificada de Ventas-Inventario-Gastos", "#ppp", :class=>"mov-suave" %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to 'Comunicarse con Nosotros', new_principal_path, remote: true %>
            </li>
          </ul>
        </li>
        <li><a href="#">¿Quienes Somos?<span class="sr-only">(current)</span></a></li>
<!--        <li><a href="#">Obtenga un Regalo!</a></li> -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!--<li><a href="#">Link</a></li> -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Clientes <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Ingresa al Sistema</a></li>
            <li><a href="#">Modificar Datos</a></li>
            <li><a href="#">Ingresar al Blog</a></li>
            <li class="divider"></li>
            <li><a href="#">Salir del Sistema</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <div class="container redes-soc">
    <div class="row">
      <div class="col-sm-1">
        <div class="sidebar-nav-fixed affix">
          <div class="well" style="padding-left: 3px;padding-right: 3px;padding-top: 10px;padding-bottom: 0px;background: rgba(0, 0, 0, 0);border:0px">
            <ul class="nav">
              <li class="nav-header" style="margin-bottom: 10px;">
                <a href="mailto:info@texhaarg.com" target="_blank" style="padding: 0px;background: rgba(0,0,0,0)">
                <%= image_tag "email_32.png", style: "width: 100%;" %>
                </a>
              </li>
              <div class="clear"></div>
              <li class="nav-header" style="margin-bottom: 10px;">
                <a href="http://www.linkedin.com/company/3374515?trk=tyah&amp;trkInfo=tas%3Atexha%20%2Cidx%3A1-2-2" target="_blank" style="padding: 0px;background: rgba(0,0,0,0)">
                  <%= image_tag "linkedin_32.png", style: "width: 100%;" %></i>
                </a>
              </li>
              <div class="clear"></div>
              <li class="nav-header" style="margin-bottom: 10px;">
                <a href="http://www.facebook.com/texhaarg" target="_blank"  style="padding: 0px;background: rgba(0,0,0,0)">
                  <%= image_tag "facebook_32.png", style: "width: 100%;" %></i>
                </a>
              </li>
              <div class="clear"></div>
              <li class="nav-header" style="margin-bottom: 10px;">
                <a href="http://www.twitter.com/texhaarg" target="_blank"  style="padding: 0px;background: rgba(0,0,0,0)">
                  <%= image_tag "twitter_32.png", style: "width: 100%;" %></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

<div class="div-ppal">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/canvas02-application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Texha Pymes</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="product-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<nav id="myNavmenu" class="navmenu navmenu-default navmenu-fixed-left offcanvas" role="navigation">
  <ul class="nav navmenu-nav">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">VENTAS <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to "Diseño Web", "#pp", :class=>"mov-suave" %>
        </li>
        <li>
          <%= link_to "Camaras de Vigilancia", "#pp", :class=>"mov-suave" %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to 'Comunicarse con Nosotros', new_principal_path, remote: true %>
        </li>
      </ul>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">COSTOS <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to "Reduccion de Costos", "#ppp", :class=>"mov-suave" %>
        </li>
        <li>
          <%= link_to "Informacion Unificada de Ventas-Inventario-Gastos", "#ppp", :class=>"mov-suave" %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to 'Comunicarse con Nosotros', new_principal_path, remote: true %>
        </li>
      </ul>
    </li>
    <li><a href="#">¿Quienes Somos?<span class="sr-only">(current)</span></a></li>
<!--        <li><a href="#">Obtenga un Regalo!</a></li> -->
  </ul>
  <ul class="nav navmenu-nav navmenu-right">
    <!--<li><a href="#">Link</a></li> -->
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Clientes <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li><a href="#">Ingresa al Sistema</a></li>
        <li><a href="#">Modificar Datos</a></li>
        <li><a href="#">Ingresar al Blog</a></li>
        <li class="divider"></li>
        <li><a href="#">Salir del Sistema</a></li>
      </ul>
    </li>
  </ul>
</nav>

<div class="navbar navbar-default navbar-fixed-top">
  <button type="button" class="navbar-toggle" data-toggle="offcanvas" data-recalc="false" data-target="#myNavmenu" data-canvas="body">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to image_tag("texhablanco100x40.jpg"), "#pp0", :class=>"navbar-brand mov-suave" %>
</div>

<div class="container redes-soc">
  <div class="row">
    <div class="col-sm-1">
      <div class="sidebar-nav-fixed affix">
        <div class="well" style="padding-left: 3px;padding-right: 3px;padding-top: 10px;padding-bottom: 0px;background: rgba(0, 0, 0, 0);border:0px">
          <ul class="nav">
            <li class="nav-header" style="margin-bottom: 10px;">
              <a href="mailto:info@texhaarg.com" target="_blank" style="padding: 0px;background: rgba(0,0,0,0)">
              <%= image_tag "email_32.png", style: "width: 100%;" %>
              </a>
            </li>
            <div class="clear"></div>
            <li class="nav-header" style="margin-bottom: 10px;">
              <a href="http://www.linkedin.com/company/3374515?trk=tyah&amp;trkInfo=tas%3Atexha%20%2Cidx%3A1-2-2" target="_blank" style="padding: 0px;background: rgba(0,0,0,0)">
                <%= image_tag "linkedin_32.png", style: "width: 100%;" %></i>
              </a>
            </li>
            <div class="clear"></div>
            <li class="nav-header" style="margin-bottom: 10px;">
              <a href="http://www.facebook.com/texhaarg" target="_blank"  style="padding: 0px;background: rgba(0,0,0,0)">
                <%= image_tag "facebook_32.png", style: "width: 100%;" %></i>
              </a>
            </li>
            <div class="clear"></div>
            <li class="nav-header" style="margin-bottom: 10px;">
              <a href="http://www.twitter.com/texhaarg" target="_blank"  style="padding: 0px;background: rgba(0,0,0,0)">
                <%= image_tag "twitter_32.png", style: "width: 100%;" %></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="div-ppal">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/materialize-css-application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Texha Pymes</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul id="menu-vtas" class="dropdown-content">
  <li>
    <%= link_to "Diseño Web", "#pp", :id=>"vermas1" %>
  </li>
  <li>
    <%= link_to "Camaras de Vigilancia", "#ppp", :id=>"vermas2" %>
  </li>
  <li class="divider"></li>
  <li>
    <%= link_to 'Comunicarse con Nosotros', new_principal_path, remote: true %>
  </li>
</ul>

<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper">
      <%= link_to image_tag("texhablanco100x40.jpg"), principals_path, :class=>"brand-logo" %>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
      <ul class="right hide-on-med-and-down">
        <li><a class="dropdown-button" href="#!" data-activates="menu-vtas">+Ventas<i class="mdi-navigation-arrow-drop-down right"></i></a></li>
        <li><a href="sass.html">Sass</a></li>
        <li><a href="components.html">Components</a></li>
        <li><a href="javascript.html">Javascript</a></li>
        <li><a href="mobile.html">Mobile</a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a class="dropdown-button" href="#!" data-activates="menu-vtas">+Ventas<i class="mdi-navigation-arrow-drop-down right"></i></a></li>
        <li><a href="sass.html">Sass</a></li>
        <li><a href="components.html">Components</a></li>
        <li><a href="javascript.html">Javascript</a></li>
        <li><a href="mobile.html">Mobile</a></li>
      </ul>
    </div>
  </nav>
</div>

<!--
<nav class="navbar navbar-default navbar-fixed-top col-xs-9 col-sm-9 col-md-9 col-lg-9">
  <div class="container-fluid">
-->
    <!-- Brand and toggle get grouped for better mobile display -->
<!--
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("texhablanco100x40.jpg"), principals_path, :class=>"navbar-brand" %>
    </div>
-->
    <!-- Collect the nav links, forms, and other content for toggling -->
<!--
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">VENTAS <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Diseño Web</a></li>
            <li><a href="#">Camaras de Vigilancia</a></li>
            <li><a href="#">Informacion Unificada de Ventas-Inventario-Gastos</a></li>
            <li class="divider"></li>
            <li><a href="#">Mas Informacion</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">COSTOS <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Reduccion de Costos</a></li>
            <li><a href="#">Informacion Unificada de Ventas-Inventario-Gastos</a></li>
            <li class="divider"></li>
            <li><a href="#">Mas Informacion</a></li>
          </ul>
        </li>
        <li><a href="#">¿Quienes Somos?<span class="sr-only">(current)</span></a></li>
-->
<!--        <li><a href="#">Obtenga un Regalo!</a></li> 
-->
<!--
      </ul>
      <ul class="nav navbar-nav navbar-right">
-->
<!--    <li><a href="#">Link</a></li> 
-->
<!--
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Clientes <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Ingresa al Sistema</a></li>
            <li><a href="#">Modificar Datos</a></li>
            <li><a href="#">Ingresar al Blog</a></li>
            <li class="divider"></li>
            <li><a href="#">Salir del Sistema</a></li>
          </ul>
        </li>
      </ul>
    </div>--> <!-- /.navbar-collapse -->
<!--  </div>--><!-- /.container-fluid -->
<!--</nav> -->

  <div class="container redes-soc">
    <div class="row">
      <div class="col-sm-1">
        <div class="sidebar-nav-fixed affix">
          <div class="well" style="padding-left: 3px;padding-right: 3px;padding-top: 10px;padding-bottom: 0px;background: rgba(0, 0, 0, 0);border:0px">
            <ul class="nav">
              <li class="nav-header" style="margin-bottom: 10px;">
                <a href="mailto:info@texhaarg.com" target="_blank" style="padding: 0px;background: rgba(0,0,0,0)">
                <%= image_tag "email_32.png", style: "width: 100%;" %>
                </a>
              </li>
              <div class="clear"></div>
              <li class="nav-header" style="margin-bottom: 10px;">
                <a href="http://www.linkedin.com/company/3374515?trk=tyah&amp;trkInfo=tas%3Atexha%20%2Cidx%3A1-2-2" target="_blank" style="padding: 0px;background: rgba(0,0,0,0)">
                  <%= image_tag "linkedin_32.png", style: "width: 100%;" %></i>
                </a>
              </li>
              <div class="clear"></div>
              <li class="nav-header" style="margin-bottom: 10px;">
                <a href="http://www.facebook.com/texhaarg" target="_blank"  style="padding: 0px;background: rgba(0,0,0,0)">
                  <%= image_tag "facebook_32.png", style: "width: 100%;" %></i>
                </a>
              </li>
              <div class="clear"></div>
              <li class="nav-header" style="margin-bottom: 10px;">
                <a href="http://www.twitter.com/texhaarg" target="_blank"  style="padding: 0px;background: rgba(0,0,0,0)">
                  <%= image_tag "twitter_32.png", style: "width: 100%;" %></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

<div class="div-ppal">
  <%= yield %>
</div>

</body>
</html>